### ISSUE TITLE
Failed to run ofp_sniffer

### ISSUE THREAD

**Issue by beraldoleal** [amlight/ofp_sniffer#7]
Hi guys, since that you are also using python3.6, looks like you have to enforce the env for use python3.6, just in case the user has python3.6 and is not the default env.

```
#!/usr/bin/env python3.6
```

```
Traceback (most recent call last):
  File "./ofp_sniffer.py", line 12, in <module>
    from libs.core.printing import PrintingOptions
  File "/tmp/ofp_sniffer/libs/core/printing.py", line 7
    class PrintingOptions(metaclass=Singleton):
                                   ^
SyntaxError: invalid syntax
```

**Comment by jab1982** [comment]
Done. Thanks for the suggestion Beraldo.
